### ISSUE TITLE
Issue mounting /system

### ISSUE THREAD

**Issue by BlueAmulet** [BiTGApps/BiTGApps#2]
My device is a Samsung Galaxy S5 (klte), it does not have a super partition and is not an A/B device. The installer seems to assume that the system partition is located at /system rather than /system_root, and fails to mount. Other flashables like other gapps packages or Magisk don't run into this issue. I had to edit the installer.sh to force ANDROID_ROOT to /system_root and then was able to install without issue.

**Comment by TheHitMan7** [comment]
Hi there,

Thanks for reporting. We have already fixed this issue and changes will reflect with next stable.
