### ISSUE TITLE
Bootmode Installation seemed to wipe device?

### ISSUE THREAD

**Issue by 66Leo66** [BiTGApps/BiTGApps#3]
Hisense HLTP700T, Android 8.1.0, Termux Bootmode Installation

Act: 
1. Place Package zip file and `bitgapps-config.prop` at `internal storage/BiTGApps`
2. Place bootmode.sh at `/data/BiTGapps`
3. Follow these commands
```bash
su
chmod -R 0755 /data/BiTGApps
export PATH=/data/BiTGApps:$PATH
bootmode.sh
```
4. Enter "1" without quote, no output log and returned to menu.
5. Enter "3", some errors were seen but screen cleared too fast. Like:
```
rm: module.prop resource busy (or something like this)
```
and A LOT OF `rm: readonly`
then all phone apps are not launchable and I have to reflash phone system.

**Comment by TheHitMan7** [comment]
You know it is not tested on every device out there.

```
rm: module.prop resource busy
```

From this error, it seems like some sort of mounting issues or kind of restrictive. I will fix this in next stable.

**Comment by TheHitMan7** [comment]
Also next update will introduce installation from Magisk App, both **system** and **systemless** installations available.

**Comment by 66Leo66** [comment]
> Also next update will introduce installation from Magisk App, both **system** and **systemless** installations available.

Just to confirm: does this mean that only Magisk Root is required and no custom Recovery is needed to install BiTGapps?
This is actually something I've always been looking for since my device is rooted but unable to flash a custom recovery.

**Comment by TheHitMan7** [comment]
> Just to confirm: does this mean that only Magisk Root is required and no custom Recovery is needed to install BiTGapps?

Yes

**Comment by TheHitMan7** [comment]
> This is actually something I've always been looking for since my device is rooted but unable to flash a custom recovery.

Installing using Bootmode script is the same thing. It can still let you install both **system** and **systemless**.
