### ISSUE TITLE
Installation failed on magisk

### ISSUE THREAD

**Issue by Luciogi** [BiTGApps/BiTGApps#3]
**Describe the bug**
Installation Failed
**To Reproduce**
1. Go to Magisk
2. Click on Modules
3. Install zip file

**Expected behavior**
Should be work without error

**Screenshots**
![Screenshot_20220930-231416_Magisk](https://user-images.githubusercontent.com/84625092/193331914-67b3b905-cfad-47d4-af6b-85419c39f1ea.png)

**Device information**
- Device: Redmi 9t
- OS: crDroid
- Version 12.1
- Platform arm64

**Logs**

**Additional context**

**Checklist**
- [x] All information is present
- [x] Logs are attached

**Comment by TheHitMan7** [comment]
You're suppoed to use [BiTGApps-arm64-12.1.0-v1.4_signed.zip](https://github.com/BiTGApps/BiTGApps-Release/releases/download/v1.4/BiTGApps-arm64-12.1.0-v1.4_signed.zip). Your device has **ARM64** Platform, as mentioned in bug report.

> Package you're flashing is for **ARM** Platform.

**Comment by Luciogi** [comment]
@TheHitMan7 yes you are right, it is my mistake.
