### ISSUE TITLE
Not appearing in Magisk modules list

### ISSUE THREAD

**Issue by Luciogi** [BiTGApps/BiTGApps#5]
**Describe the bug**
Installing via Magisk(Magisk Delta) , BitGapps does not appear in magisk modules list. So I am unable to delete it 

**To Reproduce**
1. Download 64bit BitGapps for arm64 Android 13
2. Install via [Magisk Delta](https://huskydg.github.io/magisk-files/)
3. Reboot
4. You BitGapps is not present in Magisk modules list, also not in `/data/adb/modules` 

**Expected behavior**
It should be visible in modules list

**Screenshots**
<img src="https://user-images.githubusercontent.com/84625092/211205507-f3068acc-a4a5-4eec-a419-6225d295f453.png" height="500px"/>

**Device information**
- Device: Redmi 9t (Chime)
- OS: Crdroid 9.0 (Android 13)
- Version: 13.0.0
- Platform: arm64

**Logs**
I will provide on demand

**Additional context**
Installed correctly

**Checklist**
- [Yes] All information is present
- [No] Logs are attached

**Comment by TheHitMan7** [comment]
Are you sure the build your are using is correct one ? There is a separate version of BiTGApps supporting systemless feature. Can you post download link ?

**Comment by Luciogi** [comment]
File name is : BiTGApps-arm64-13.0.0-v1.8_signed.zip
Sha256: 7f17df1ec202500562c1a2bba48dd60f7a6d0bfee0f9366a0376e895fce59661

**Comment by Luciogi** [comment]
Yes I installed wrong

**Comment by Luciogi** [comment]
So Tell me is there way to Reverse installation ?

**Comment by TheHitMan7** [comment]
> Yes I installed wrong

https://bitgapps.github.io/download.html

**Comment by TheHitMan7** [comment]
> So Tell me is there way to Reverse installation ?

You can try using uninstaller, if you have just BiTGApps installed.

- No Addons
- No SetupWizard

[Click here for Uninstaller!](https://github.com/BiTGApps/BiTGApps-Uninstaller/releases/download/v1.8/BiTGApps-v1.8.zip)

**Comment by Luciogi** [comment]
Yes I have only installed BitGapps

**Comment by TheHitMan7** [comment]
> Yes I have only installed BitGapps

Then proceed with uninstaller.

**Comment by Luciogi** [comment]
@TheHitMan7  Thanks alot, I thought I am fed up
